name: publish
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          docker build . --tag ghcr.io/baconbearry/symbol_price_alert:${{ github.ref }}
          docker push ghcr.io/baconbearry/symbol_price_alert:${{ github.ref }}
